version: "3.8"

services:
  node_frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - node_backend

  node_backend:
    container_name: backend
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=MascotasDB
      - PGUSER=service
      - PGPASSWORD=Pass12345+
      - PGHOST=node_db
    volumes:
      - ./backend:/backend

#   node_db:
#     image: postgres
#     container_name: local_pgdb
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: service
#       POSTGRES_PASSWORD: Pass12345+
#     volumes:
#       - local_pgdata:/var/lib/postgresql/data
  
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin4_container
#     restart: always
#     ports:
#       - "8888:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
#       PGADMIN_DEFAULT_PASSWORD: Pass12345+
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin

# volumes:
#   local_pgdata:
#   pgadmin-data: