version: "3.8"

services:
  node_backend:
    container_name: backend
    image: example:0.0.5
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=MascotasDB
      - PGUSER=service
      - PGPASSWORD=Pass12345+
      - PGHOST=node_db
    depends_on:
      - node_db

  node_frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"

  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=service
      - POSTGRES_PASSWORD=Pass12345+
      - POSTGRES_DB=MascotasDB
    volumes:
      - nps_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Pass12345+
    ports:
      - 5050:80
    depends_on:
      - node_db

volumes:
  nps_data: {}
